### ISSUE TITLE
mounting paths

### ISSUE THREAD

**Issue by DocMAX** [DDoSolitary/yasfw#3]
could you add an option to mount a path? like:
server:/mnt/sshfs

**Comment by xn4rph** [comment]
+1
I really need this too because I need to write to the mounted directory, however I am mounting to Android and since it mounts at rootdir my user doesnt have write permission.

I have tried to compile this myself but got some errors and have no clue how to build it as we don't have a readme...

Thanks

**Comment by DDoSolitary** [comment]
This feature is on my to-do list, but I'm not sure when I can find some time to implement this, because currently I'm working on some other projects.

**Comment by DDoSolitary** [comment]
Added an `-C` option for this purpose in v0.1.2,
